USE [master]
GO
/****** Object:  Database [Flask]    Script Date: 12/3/2024 3:39:09 PM ******/
CREATE DATABASE [Flask]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Flask', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Flask.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Flask_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Flask_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Flask] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Flask].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Flask] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Flask] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Flask] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Flask] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Flask] SET ARITHABORT OFF 
GO
ALTER DATABASE [Flask] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Flask] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Flask] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Flask] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Flask] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Flask] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Flask] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Flask] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Flask] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Flask] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Flask] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Flask] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Flask] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Flask] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Flask] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Flask] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Flask] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Flask] SET RECOVERY FULL 
GO
ALTER DATABASE [Flask] SET  MULTI_USER 
GO
ALTER DATABASE [Flask] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Flask] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Flask] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Flask] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Flask] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Flask] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Flask', N'ON'
GO
ALTER DATABASE [Flask] SET QUERY_STORE = ON
GO
ALTER DATABASE [Flask] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Flask]
GO
/****** Object:  Table [dbo].[answers]    Script Date: 12/3/2024 3:39:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[answers](
	[id] [nvarchar](50) NOT NULL,
	[questionId] [nvarchar](50) NOT NULL,
	[answeredByUsername] [nvarchar](50) NULL,
	[answer] [nvarchar](max) NOT NULL,
	[rowNumber] [int] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[rowNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_answers_id] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[answersRating]    Script Date: 12/3/2024 3:39:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[answersRating](
	[id] [nvarchar](50) NOT NULL,
	[score] [int] NOT NULL,
	[questionId] [nvarchar](50) NOT NULL,
	[userId] [nvarchar](50) NOT NULL,
	[rowNumber] [int] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[rowNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_answersRating_id] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProfilePictures]    Script Date: 12/3/2024 3:39:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProfilePictures](
	[username] [nvarchar](50) NOT NULL,
	[photoPath] [nvarchar](max) NULL,
	[bio] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[questions]    Script Date: 12/3/2024 3:39:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[questions](
	[id] [nvarchar](50) NOT NULL,
	[questionTitle] [nvarchar](255) NOT NULL,
	[questionText] [nvarchar](max) NOT NULL,
	[askedByUsername] [nvarchar](50) NOT NULL,
	[rowNumber] [int] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[rowNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_questions_id] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 12/3/2024 3:39:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[username] [nvarchar](50) NOT NULL,
	[instagram_id] [nvarchar](50) NULL,
	[password] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[answers]  WITH CHECK ADD  CONSTRAINT [FK_answers_questions] FOREIGN KEY([questionId])
REFERENCES [dbo].[questions] ([id])
GO
ALTER TABLE [dbo].[answers] CHECK CONSTRAINT [FK_answers_questions]
GO
ALTER TABLE [dbo].[answersRating]  WITH CHECK ADD  CONSTRAINT [FK_answersRating_questions] FOREIGN KEY([questionId])
REFERENCES [dbo].[questions] ([id])
GO
ALTER TABLE [dbo].[answersRating] CHECK CONSTRAINT [FK_answersRating_questions]
GO
ALTER TABLE [dbo].[answersRating]  WITH CHECK ADD  CONSTRAINT [FK_answersRating_users] FOREIGN KEY([userId])
REFERENCES [dbo].[users] ([username])
GO
ALTER TABLE [dbo].[answersRating] CHECK CONSTRAINT [FK_answersRating_users]
GO
ALTER TABLE [dbo].[ProfilePictures]  WITH CHECK ADD  CONSTRAINT [FK_photo_user] FOREIGN KEY([username])
REFERENCES [dbo].[users] ([username])
GO
ALTER TABLE [dbo].[ProfilePictures] CHECK CONSTRAINT [FK_photo_user]
GO
USE [master]
GO
ALTER DATABASE [Flask] SET  READ_WRITE 
GO
